<div class="outer">
    <div class="middle">
        <div class="inner">
            <div>
                <input type="number" id="amount" placeholder="0">
                <select class="currencyField" id="currencyIn"></select>
                <span>to</span>
                <select class="currencyField" id="currencyOut"></select>
                <button id="SwapButton">Swap</button>
                <button id="convertButton">Convert</button>
            </div>
        </div>
        <div style="margin-left: auto;margin-right: auto;width: 50%;text-align: center;">
            <div id="result">
                <div></div>
            </div>
            <div id="history"></div>
        </div>

    </div>
</div>
<div id="last-update-time">
    <div>Currency rates by Yahoo Finance on:</div>
    <div id="update-time">...loading</div>
    <div>UTC/GMT +3</div>
</div>
