<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#2196F3">
    <title>Currency Converter</title>
    <script defer src="js/main.js"></script>
    <script defer
            src="https://code.jquery.com/jquery-1.9.1.min.js"
            integrity="sha256-wS9gmOZBqsqWxgIVgA8Y9WcQOa7PgSIX+rPA0VL2rbQ="
            crossorigin="anonymous" onload="init()"></script>
    <link rel="stylesheet" type="text/css" href="css/main.css">

</head>
<body>

<?php echo $this->layout()->content ?>

</body>
</html>